GET http://localhost:3000/user/list

###
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "name": "newuser4",
  "email": "newuser4@example.com",
  "password": "password",
  "address": "disini3"
}
