### Get User List
GET http://localhost:3000/user/list?sb=name&ob=ASC&lt=3

### Get User By Id
GET http://localhost:3000/user/1

### Register User
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "name": "newuser5",
  "email": "newuser5@example.com",
  "password": "password",
  "address": "disini3",
  "photo": "ini",
  "card_type":"visa",
  "card_number":"12312313",
  "card_name":"bris",
  "card_expired":"-",
  "card_cvv":"211"
}


### Update User
PATCH  http://localhost:3000/user/1
Content-Type: application/json

{
  "name": "user 1",
  "password": "password",
  "address": "alamat user1"
}
